<a href="https://colab.research.google.com/github/Josesilva793/Josesilva793/blob/main/Obesity_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip -q install plotly

In [3]:
!pip -q install yellowbrick

In [4]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

In [6]:
train = pd.read_csv('/content/train.csv')

In [99]:
test

id  Gender        Age    Height      Weight  \
0          0    Male  24.443011  1.699998   81.669950   
1          1  Female  18.000000  1.560000   57.000000   
2          2  Female  18.000000  1.711460   50.165754   
3          3  Female  20.952737  1.710730  131.274851   
4          4    Male  31.641081  1.914186   93.798055   
...      ...     ...        ...       ...         ...   
20753  20753    Male  25.137087  1.766626  114.187096   
20754  20754    Male  18.000000  1.710000   50.000000   
20755  20755    Male  20.101026  1.819557  105.580491   
20756  20756    Male  33.852953  1.700000   83.520113   
20757  20757    Male  26.680376  1.816547  118.134898   

      family_history_with_overweight FAVC      FCVC       NCP        CAEC  \
0                                yes  yes  2.000000  2.983297   Sometimes   
1                                yes  yes  2.000000  3.000000  Frequently   
2                                yes  yes  1.880534  1.411685   Sometimes   
3                                yes  yes  3.000000  3.000000   Sometimes   
4                                yes  yes  2.679664  1.971472   Sometimes   
...                              ...  ...       ...       ...         ...   
20753                            yes  yes  2.919584  3.000000   Sometimes   
20754                             no  yes  3.000000  4.000000  Frequently   
20755                            yes  yes  2.407817  3.000000   Sometimes   
20756                            yes  yes  2.671238  1.971472   Sometimes   
20757                            yes  yes  3.000000  3.000000   Sometimes   

      SMOKE      CH2O SCC       FAF       TUE       CALC  \
0        no  2.763573  no  0.000000  0.976473  Sometimes   
1        no  2.000000  no  1.000000  1.000000         no   
2        no  1.910378  no  0.866045  1.673584         no   
3        no  1.674061  no  1.467863  0.780199  Sometimes   
4        no  1.979848  no  1.967973  0.931721  Sometimes   
...     ...       ...  ..       ...       ...        ...   
20753    no  2.151809  no  1.330519  0.196680  Sometimes   
20754    no  1.000000  no  2.000000  1.000000  Sometimes   
20755    no  2.000000  no  1.158040  1.198439         no   
20756    no  2.144838  no  0.000000  0.973834         no   
20757    no  2.003563  no  0.684487  0.713823  Sometimes   

                      MTRANS           NObeyesdad  
0      Public_Transportation  Overweight_Level_II  
1                 Automobile        Normal_Weight  
2      Public_Transportation  Insufficient_Weight  
3      Public_Transportation     Obesity_Type_III  
4      Public_Transportation  Overweight_Level_II  
...                      ...                  ...  
20753  Public_Transportation      Obesity_Type_II  
20754  Public_Transportation  Insufficient_Weight  
20755  Public_Transportation      Obesity_Type_II  
20756             Automobile  Overweight_Level_II  
20757  Public_Transportation      Obesity_Type_II  

[20758 rows x 18 columns]

In [12]:
test.describe()

id           Age        Height        Weight          FCVC  \
count  20758.00000  20758.000000  20758.000000  20758.000000  20758.000000   
mean   10378.50000     23.841804      1.700245     87.887768      2.445908   
std     5992.46278      5.688072      0.087312     26.379443      0.533218   
min        0.00000     14.000000      1.450000     39.000000      1.000000   
25%     5189.25000     20.000000      1.631856     66.000000      2.000000   
50%    10378.50000     22.815416      1.700000     84.064875      2.393837   
75%    15567.75000     26.000000      1.762887    111.600553      3.000000   
max    20757.00000     61.000000      1.975663    165.057269      3.000000   

                NCP          CH2O           FAF           TUE  
count  20758.000000  20758.000000  20758.000000  20758.000000  
mean       2.761332      2.029418      0.981747      0.616756  
std        0.705375      0.608467      0.838302      0.602113  
min        1.000000      1.000000      0.000000      0.000000  
25%        3.000000      1.792022      0.008013      0.000000  
50%        3.000000      2.000000      1.000000      0.573887  
75%        3.000000      2.549617      1.587406      1.000000  
max        4.000000      3.000000      3.000000      2.000000

In [13]:
test.isnull().sum()

id                                0
Gender                            0
Age                               0
Height                            0
Weight                            0
family_history_with_overweight    0
FAVC                              0
FCVC                              0
NCP                               0
CAEC                              0
SMOKE                             0
CH2O                              0
SCC                               0
FAF                               0
TUE                               0
CALC                              0
MTRANS                            0
NObeyesdad                        0
dtype: int64

In [15]:
test.columns

Index(['id', 'Gender', 'Age', 'Height', 'Weight',
       'family_history_with_overweight', 'FAVC', 'FCVC', 'NCP', 'CAEC',
       'SMOKE', 'CH2O', 'SCC', 'FAF', 'TUE', 'CALC', 'MTRANS', 'NObeyesdad'],
      dtype='object')

In [131]:
x_test = test.iloc[:, 0:17].values

In [132]:
x_test[0]

array([0, 'Male', 24.443011, 1.699998, 81.66995, 'yes', 'yes', 2.0,
       2.983297, 'Sometimes', 'no', 2.763573, 'no', 0.0, 0.976473,
       'Sometimes', 'Public_Transportation'], dtype=object)

In [133]:
y_test = test.iloc[:,17].values

In [134]:
y_test

array(['Overweight_Level_II', 'Normal_Weight', 'Insufficient_Weight', ...,
       'Obesity_Type_II', 'Overweight_Level_II', 'Obesity_Type_II'],
      dtype=object)

In [66]:
from sklearn.preprocessing import LabelEncoder

In [102]:
label_encoder_Gender = LabelEncoder() # colunm 1
label_encoder_family_history_with_overweight = LabelEncoder() # colunm 5
label_encoder_FAVC = LabelEncoder() # colunm 6
label_encoder_CAEC = LabelEncoder() # colunm 9
label_encoder_SMOKE = LabelEncoder() # colunm 10
label_encoder_SCC = LabelEncoder() # colunm 12
label_encoder_CALC = LabelEncoder() # colunm 15
label_encoder_MTRANS = LabelEncoder() # colunm 16
label_encoder_NObeyesdad = LabelEncoder() # colunm 17

In [167]:
x_test[:,1] = label_encoder_Gender.fit_transform(x_test[:,1])
x_test[:,5] = label_encoder_family_history_with_overweight.fit_transform(x_test[:,5])
x_test[:,6] = label_encoder_FAVC.fit_transform(x_test[:,6])
x_test[:,9] = label_encoder_CAEC.fit_transform(x_test[:,9])
x_test[:,10] = label_encoder_SMOKE.fit_transform(x_test[:,10])
x_test[:,12] = label_encoder_SCC.fit_transform(x_test[:,12])
x_test[:,15] = label_encoder_CALC.fit_transform(x_test[:,15])
x_test[:,16] = label_encoder_MTRANS.fit_transform(x_test[:,16])


In [168]:
x_test[0]

array([0.0, 1, 1.0, 0.0, 0.0, 1, 0, 1.0, 1.0, 0, 0, 1.0, 1, 0.0, 1.0, 0,
       0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0,
       0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0,
       0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0,
       24.443011, 1.699998, 81.66995, 2.0, 2.983297, 2.763573, 0.0,
       0.976473], dtype=object)

In [107]:
len(np.unique(test['Gender']))

2

In [108]:
len(np.unique(test['family_history_with_overweight']))

2

In [109]:
len(np.unique(test['FAVC']))

2

In [110]:
len(np.unique(test['CAEC']))

4

In [111]:
len(np.unique(test['SMOKE']))

2

In [112]:
len(np.unique(test['SCC']))

2

In [113]:
len(np.unique(test['CALC']))

3

In [114]:
len(np.unique(test['MTRANS']))

5

In [169]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [170]:
onehotencoder_test = ColumnTransformer(transformers=[('onehot',OneHotEncoder(), [1,5,6,9,10,12,15,16])],remainder='passthrough')

In [174]:
x_test = onehotencoder_test.fit_transform(x_test)

In [176]:
x_test = np.asarray(x_test)

In [177]:
x_test[3]

array([1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0,
       1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0,
       0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0,
       1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0,
       0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0,
       0.0, 0.0, 0.0, 1.0, 0.0, 3, 20.952737, 1.71073, 131.274851, 3.0,
       3.0, 1.674061, 1.467863, 0.780199], dtype=object)

In [178]:
from sklearn.preprocessing import StandardScaler
scaler_census = StandardScaler()
x_test = scaler_census.fit_transform(x_test)

In [179]:
x_test[3]

array([ 0.99586557, -0.99586557,  0.61465789, -0.61465789, -0.57538478,
        0.57538478, -0.99586557,  0.99586557, -0.99586557,  0.99586557,
        0.99586557, -0.99586557, -0.99586557,  0.99586557, -0.99586557,
        0.99586557,  0.99586557, -0.18500943,  0.18500943,  0.61465789,
       -0.57538478, -0.99586557, -0.99586557,  0.99586557, -0.99586557,
        0.10928699, -0.10928699, -0.18500943,  0.61465789,  0.57538478,
       -0.99586557,  0.99586557, -0.99586557, -0.11672066,  0.11672066,
        0.10928699, -0.18500943, -0.61465789,  0.57538478,  0.99586557,
       -0.99586557,  0.15352531, -0.15352531, -0.11672066,  0.10928699,
        0.18500943, -0.61465789, -0.57538478, -0.99586557, -0.30587959,
        0.30587959,  0.15352531, -0.11672066, -0.10928699,  0.18500943,
        0.61465789,  0.57538478, -0.46909921,  0.46909921, -0.30587959,
       -0.36767566,  0.42919579, -0.10928699, -0.18500943, -0.1617114 ,
       -0.45296669, -0.03929319, -0.04282496,  0.49392547, -0.15